# Generated by Django 4.2.14 on 2025-04-01 12:07

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CybercrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(choices=[('phishing', 'Phishing'), ('hacking', 'Hacking'), ('malware', 'Malware'), ('identity_theft', 'Identity Theft'), ('cyberbullying', 'Cyberbullying'), ('online_fraud', 'Online Fraud'), ('data_breach', 'Data Breach'), ('others', 'Others')], max_length=20)),
                ('incident_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.evidence_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='core.cybercrimereport')),
            ],
        ),
    ]
