# Generated by Django 5.2 on 2025-04-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cybercrimereport_browser_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cybercrimereport',
            options={'ordering': ['-priority_score', '-submitted_at']},
        ),
        migrations.AddField(
            model_name='cybercrimereport',
            name='priority_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
