# Generated by Django 4.2.14 on 2025-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cybercrimereport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybercrimereport',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cybercrimereport',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cybercrimereport',
            name='priority_level',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='cybercrimereport',
            name='resolution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
